Fix merge hdr step during report processing [DEX-375] (#2269)
Fix to __merge_worker_hdr step: Write all files list into a file and
read from that file while processing in Java.

I also added some extra logs during hdr merge step to understand the
progress since this step lasts too long. I write the log after each
merged hdr like this:
```
INFO  23:20:01 [2025-04-18 23:20:01] [HistogramLogMerger] Added merged histogram 1082 to run_dir/map.get.hdr
```

With this fix, the report generation can be run on lab servers. I ran it
on lab server 1. I was able to generate the 12k report on lab server 101
in 1.5 hours.
```
47413.55user 4561.21system 1:30:34elapsed 956%CPU
```

Out of this 1/5 hours, 
- 30 mins is hdr_merge step. 
- 20 mins: Processing hdr files: Done 1219.31 seconds
- 6 mins: Loading csv files.
- 26 mins: Writing combined run data to:
/home/ihsan/hazelcast-simulator/tmp/my_report/data.csv
- 7 min : Generating png files.

Given these times. The next improvement for further speedup would be to
focus on the highest ones and see if we can speed them up. For example,
the step `Writing combined run data to:
/home/ihsan/hazelcast-simulator/tmp/my_report/data.csv` taking 26 mins
seems like a candidate for improvement.

The problem without the fix was:

```
INFO  11:28:25 Using the following run:
INFO  11:28:25        09-04-2025_12-47-55 runs/3k_clients_test_near_cache_disabled/09-04-2025_12-47-55
INFO  11:28:27  Merging operations dataframes
INFO  11:28:30 Completed merging operations dataframes
INFO  11:28:30  Finished merging dataframes in 2.5143046379089355 seconds.
INFO  11:28:30 Starting worker hdr file merge
Traceback (most recent call last):
  File "/home/ihsan/hazelcast-simulator/bin/../src/perftest_cli.py", line 63, in <module>
    PerftestCli()
  File "/home/ihsan/hazelcast-simulator/bin/../src/perftest_cli.py", line 37, in __init__
    getattr(self, args.command)()
  File "/home/ihsan/hazelcast-simulator/bin/../src/perftest_cli.py", line 58, in report
    PerfTestReportCli(sys.argv[2:])
  File "/home/ihsan/hazelcast-simulator/src/simulator/perftest_report.py", line 262, in __init__
    prepare(config)
  File "/home/ihsan/hazelcast-simulator/src/simulator/perftest_report.py", line 28, in prepare
    prepare_hdr(config)
  File "/home/ihsan/hazelcast-simulator/src/simulator/perftest_report_hdr.py", line 22, in prepare_hdr
    __merge_worker_hdr(run_dir)
  File "/home/ihsan/hazelcast-simulator/src/simulator/perftest_report_hdr.py", line 47, in __merge_worker_hdr
    shell(f"""java -cp "{simulator_home}/lib/*" \
  File "/home/ihsan/hazelcast-simulator/src/simulator/util.py", line 163, in shell
    process = Popen(cmd, stdout=PIPE, stderr=PIPE, shell=shell)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1022, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1899, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 7] Argument list too long: '/bin/sh'
```

---------

Co-authored-by: Artem Laktionov <laktionov_artem@ukr.net>